baseURL = "https://blog.kevinoliveira.ch/"
languageCode = "fr-ch"
title = "Kevin | Blog"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@kevoliv11"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true

[menu]

[[menu.main]]
    identifier = 'posts'
    name = 'Articles'
    url = '/posts/'
    weight = 1

  [[menu.main]]
    identifier = 'categories'
    name = 'Catégories'
    url = '/categories/'
    weight = 2

    [[menu.main]]
    identifier = 'about'
    name = 'A propos'
    url = 'pages/about/'
    weight = 3

    

  